package Admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

import Important_Classes.Flight;

/**
 *
 * @author emine
 */
public class AddFlightPage extends javax.swing.JPanel {

    /**
     * Creates new form AddFlightPage
     */
    public AddFlightPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        addNewFlightLabel = new javax.swing.JLabel();
        pilotLabel = new javax.swing.JLabel();
        pilotComboBox = new javax.swing.JComboBox<>();
        destinationLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        toComboBox = new javax.swing.JComboBox<>();
        dateLabel = new javax.swing.JLabel();
        dateTextFieldArea = new JTextField();
        timeComboBox = new javax.swing.JComboBox<>();
        timeLabel = new javax.swing.JLabel();
        planeLabel = new javax.swing.JLabel();
        planeComboBox = new javax.swing.JComboBox<>();
        fromComboBox = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        enterBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        addNewFlightLabel.setBackground(new java.awt.Color(255, 255, 255));
        addNewFlightLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addNewFlightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addNewFlightLabel.setText("Add new flight");
        addNewFlightLabel.setOpaque(true);

        pilotLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pilotLabel.setText("Pilot");

        pilotComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kerem Topuz", "Asli Sonmaz", "Ersin TurkOglu", "Ugurkan Durmaz" }));

        destinationLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinationLabel.setText("Destination");

        fromLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fromLabel.setText("From:");

        toLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toLabel.setText("To:");

        toComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "Istanbul", "Izmir", "Adana" }));

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateLabel.setText("Date");

        dateTextFieldArea.setText("MM/DD/YYYY");

        timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "05:00", "08:00", "01:00", "=3:00" }));

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        timeLabel.setText("Time");

        planeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        planeLabel.setText("Plane");

        planeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3506", "4891", "6297", "2985","5784" }));

        fromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "Istanbul", "Izmir", "Adana" }));

        backBtn.setText("<--");

        enterBtn.setText("Enter");
        enterBtn.addActionListener(new enterBtnActionPerformed());
 

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pilotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(planeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilotComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(toLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(planeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                .addComponent(timeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(addNewFlightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewFlightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilotLabel)
                    .addComponent(pilotComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLabel)
                    .addComponent(fromLabel)
                    .addComponent(toLabel)
                    .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planeLabel)
                    .addComponent(planeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(enterBtn)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    class enterBtnActionPerformed implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent event)
        {
                Flight.addFlight("3333", (String)fromComboBox.getSelectedItem(), 
                (String)toComboBox.getSelectedItem(), 
                (String)planeComboBox.getSelectedItem(),
                 "00:00", (String)timeComboBox.getSelectedItem(), (String)pilotComboBox.getSelectedItem(), "False", "False");
                 JOptionPane.showMessageDialog(null, "Flight has been created, flight will be add when the app is closed.");
        }
    } 


    public void goBackBtnListener(ActionListener event){
        backBtn.addActionListener(event);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel addNewFlightLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel dateLabel;
    private JTextField dateTextFieldArea;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JButton enterBtn;
    private javax.swing.JComboBox<String> fromComboBox;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JComboBox<String> pilotComboBox;
    private javax.swing.JLabel pilotLabel;
    private javax.swing.JComboBox<String> planeComboBox;
    private javax.swing.JLabel planeLabel;
    private javax.swing.JComboBox<String> timeComboBox;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JComboBox<String> toComboBox;
    private javax.swing.JLabel toLabel;
    // End of variables declaration            
    
    



}