package Admin;

import java.awt.event.ActionListener;
import java.util.ArrayList;

import GUI_elements.TypePanels.FlightsPanel;
import Important_Classes.Flight;

/**
 *
 * @author emine
 */
public class ManageFlightsPage extends javax.swing.JPanel {

    /**
     * Creates new form ManageFlightsPage
     */
    public ArrayList<Flight> flights = FlightsPanel.flightsList;

    public ManageFlightsPage() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageFlightsTable = new javax.swing.JTable();
        deleteFlightBtn = new javax.swing.JButton();
        addFlightBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        username.setBackground(new java.awt.Color(153, 255, 102));
        username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Manage Flights");
        username.setOpaque(true);

        String[][] listing = new String[flights.size()][6];

        for (int i = 0; i < flights.size(); i++) {
            
            listing[i][0] = flights.get(i).getFlightCode();
            listing[i][1] = flights.get(i).getDepartureTime();
            listing[i][2] = flights.get(i).getArrivalTime();
            listing[i][3] = flights.get(i).getPilotName();
            listing[i][4] = flights.get(i).getPlaneID();
            listing[i][5] = flights.get(i).getIsSafe();

            
        }


        manageFlightsTable.setModel(new javax.swing.table.DefaultTableModel(listing,
            new String [] {
                "Flight", "Arrival Time", "Departure Time", "Pilot", "Plane ID", "Plane Readiness"
            }
        ));
        jScrollPane1.setViewportView(manageFlightsTable);

        deleteFlightBtn.setText("delete flight");


        addFlightBtn.setText("add new flight");


        backBtn.setText("<--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addFlightBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deleteFlightBtn))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFlightBtn)
                    .addComponent(addFlightBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    public void addFlightBtnActionPerformed(ActionListener evt) {  
        
        addFlightBtn.addActionListener(evt);
        // TODO add your handling code here:
    }                                            

    public void deleteFlightBtnActionPerformed(ActionListener evt) {                                                
        // TODO add your handling code here:
        deleteFlightBtn.addActionListener(evt);
    }                                               

    // Variables declaration - do not modify                     
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteFlightBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageFlightsTable;
    private javax.swing.JLabel username;
    // End of variables declaration                   


    //Listener to be implemented on go back button
    public void goBackBtnListener(ActionListener event) {
        backBtn.addActionListener(event);
    }
    //Listener to be implemented on add flights button
  
}
