package Main;

import Login.*;
import Admin.*;
import GUI_elements.HomePage.HomePanel2;
import GUI_elements.HomePage.testHomepage;
import GUI_elements.TypePanels.FlightsPanel;
import Pilot.*;
import Maintenance.*;
import Profile.*;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import Accounts.Account;

public class Frame extends javax.swing.JFrame {
  
    private Account user = null;

    public Frame() {
        initComponents();

        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        Login login = new Login();

        login.getPasswords();
        login.getUserIDs();
        login.getNames();
        login.getSurNames();
        login.getRoles();
        
        AdminPanel adminPanel = new AdminPanel(user);
        AddFlightPage addFlightPage = new AddFlightPage();
        DeleteFlightPage deleteFlight = new DeleteFlightPage();
        ManageFlightsPage manageFlightsPage = new ManageFlightsPage();
        PilotPanel pilotPanel = new PilotPanel();
        MaintenancePanel maintenancePanel = new MaintenancePanel();
        //ProfilePanel profilePanel = new ProfilePanel();
        AboutUs aboutUs = new AboutUs();
        Feedback feedback = new Feedback();
        
        testHomepage homepage = new testHomepage();
        
        slide.setAnimate(20);
        slide.init(login, homepage , adminPanel, addFlightPage, deleteFlight, manageFlightsPage, pilotPanel,
                maintenancePanel,aboutUs, feedback);
        login.addHomepageListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae){
                slide.show(1);
        }
        });
        adminPanel.goBackBtnListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae){
                slide.show(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        pack();
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(Exception ex) {
            System.out.println(ex.getStackTrace());
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.PanelGradiente panelGradiente1;
    private swing.PanelSlide slide;
    // End of variables declaration//GEN-END:variables
}