
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JPanel;

import AGS.EmailSender.HealthReportSender;


/*Specified panel for the particular role
 * 
 * 
 */
public class PilotPanel extends JPanel {

    private PilotAccount user;

        // Variables declaration - do not modify                     
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        // End of variables declaration  

        private String fileName;


        /**
         * Creates new form PilotPanel
         */
        public PilotPanel(PilotAccount pilot) {

            this.user = pilot;
            initComponents();
        }
    
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {
    
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
    
            addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    formMouseClicked(evt);
                }
            });
    
            jLabel1.setText("Welcome to AGS PilotUSername,");
    
            jLabel2.setText("Your have to add a user report in ... days");
    
            jButton1.setText("add report");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
    
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(jButton1)))
                    .addContainerGap(9, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addContainerGap(33, Short.MAX_VALUE))
            );
        }// </editor-fold>                        
    
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            if(f != null && f.canRead())
            {
                fileName = f.getAbsolutePath();
                System.out.println(fileName);
                System.out.println("Button works!");
                HealthReportSender.SendHealthReport(fileName, user);

            }

        }                                        
    
        private void formMouseClicked(java.awt.event.MouseEvent evt) {                                  
  


            HealthReportSender.SendHealthReport(fileName, user);

        }                                 
    
    
                 
    }
    
